# Publish all joint states
rover_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Rover velocity controller used by navigation stack
rover_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['left_bogie_front_axle', 'left_bogie_rear_axle', 'left_rocker_rear_axle']
  right_wheel: ['right_bogie_front_axle', 'right_bogie_rear_axle', 'right_rocker_rear_axle']

  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  k_l: 0.1
  k_r: 0.1

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.5 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2
